services:
    dbhost:
      image: quanticschoolofbusiness/103mysql
    app:
      build: app/.
      ports: 
        - 3006:3006
      depends_on:
        - dbhost
        - redis-server
    redis-server:
      image: redis
    email:
      build: email/.
      ports: 
        - 25:25
      depends_on:
        - redis-server
      environment:
        TO_ADDRESS: sj73@students.quantic.edu
        FROM_ADDRESS: stephen.jacildo.cac@gmail.com
        FROM_PASSWORD: cgcuteevgycqogup
    db-loader:
      build: db-loader/.
      volumes: 
        - D:/Programming/Quantic/microservices/allergy-lab-watchfolder:/mnt/watchfolder/
      environment:
        FOLDER_PATH: /mnt/watchfolder/
        DB_NAME: allergen_info
        DB_USER: pythonapp
        DB_PASS: secretPass123!
      depends_on:
        - dbhost